version: '3.4'

volumes:
  mongo_vol:


networks:
  produto_net:
    driver: bridge

services:
  api:
    image: danielbombonate/api-produto:v1.0
    environment:
      MONGODB_URI: mongodb://mongouser:mongopwd@mongodb:27017/admin
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - produto_net

  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017
    networks:
      - produto_net
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
